---
title: "Empirical estimates of variance inflation factors"
subtitle: 'Examine 4 dataset'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
  self_contained: false
---



<!---

cd /Users/gabrielhoffman/workspace/repos/dreamlet_analysis/delta_method
# cd /hpc/users/hoffmg01/www/dreamlet_analysis/delta_method

ml python git pandoc 
ml gcc/11.2.0
git pull 

rmarkdown::render("empirical_vif.Rmd")


--->
 

```{r knitr, echo=FALSE, message=FALSE}
suppressPackageStartupMessages(library(knitr))
options(xtable.type="html")

knitr::opts_chunk$set(
  echo=TRUE,
  warning=FALSE,
  message=TRUE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE,
  cache.lazy = FALSE,
  dev = c("png", "pdf"), 
  fig.width=7, fig.height=7)
```

```{r library, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(ggplot2)
library(dreamlet)
library(DelayedArray)
```

# Kfoury_CancerCell_2021
```{r Kfoury}
setAutoBlockSize(1e9)

file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/Kfoury_CancerCell_2021/Kfoury_CancerCell_2021.h5ad"
sce = readH5AD(file, use_hdf5=TRUE)   

sce$cells = factor(sce$cells, sort(levels(sce$cells)))

# create pseudobulk 
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "cells",  
    sample_id = "ID")

# compute weights
weightsList <- pbWeights(sce,
  cluster_id = "cells", 
  sample_id = "ID",
  details=TRUE)

# process expression to get genes with sufficient expression
res.proc <- processAssays(pb, ~1)
```

# Nathan_NatImm_2021
```{r Nathan}
path = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/Nathan_NatImm_2021/"
file = paste0(path, "/Nathan_NatImm_2021.h5ad")
sce = readH5AD(file, use_hdf5=TRUE)   

# get only single-cell RNA-seq
# rest is CITE-seq proteins
only_rna = grep("prot", rownames(sce), invert=TRUE)

# create variable that distinguishes cells from the same donor
# but different batches
sce$donor_batch = with(colData(sce), paste(donor, batch))
sce$batch = factor(sce$batch)
sce$season = factor(sce$season)
sce$TB_status = factor(sce$TB_status, c("CONTROL", "CASE"))

# sort cell clusters by name
sce = sce[only_rna,sce$cluster_name != "NA"]
colData(sce) = droplevels(colData(sce))
tab = colData(sce) %>%
  as_tibble %>%
  group_by(cluster_ids, cluster_name) %>%
  filter(row_number()==1) %>%
  summarise(cluster_ids, cluster_name) %>%
  arrange(as.numeric(gsub("C-", '', cluster_ids)))

sce$cluster_name = factor(sce$cluster_name, unique(tab$cluster_name))
sce$cluster_ids = factor(sce$cluster_ids, unique(tab$cluster_ids))

# create pseudobulk 
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "cluster_name",  
    sample_id = "donor_batch")

# compute weights
weightsList <- pbWeights(sce,
  cluster_id = "cluster_name",
  sample_id = "donor_batch", 
  details=TRUE)

# process expression to get genes with sufficient expression
res.proc <- processAssays(pb, ~1)
```


# PsychAD pr0
```{r PsychAD}
folder = "/sc/arion/projects/psychAD/NPS-AD/public_release_0/" 
file = paste0(folder, "PsychAD_r0_Dec_28_2022.h5ad")
sce = readH5AD(file, use_hdf5=TRUE, verbose=TRUE)
assayNames(sce)[1] = "counts"
sce$Dx = factor(sce$Dx_AD, c('Control','AD'))

# Create pseudo-bulk SingleCellExperiment
pb = aggregateToPseudoBulk(sce,
    assay = "counts", 
    cluster_id = "subclass",
    sample_id = "Channel",
    BPPARAM = SnowParam(6))

# compute weights
weightsList <- pbWeights(sce,
  cluster_id = "subclass", 
  sample_id = "Channel",
  details=TRUE)

# process expression to get genes with sufficient expression
res.proc <- processAssays(pb, ~1)
```



















